volumes:
  redis_data:
  agent_data:

services:

  # main voiceaiagent service
  voiceaiagent-app:
    image: voiceaiagent-app
    build:
      context: ..
      dockerfile: local_setup/dockerfiles/voiceaiagent-app.Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    env_file:
        - .env
    volumes:
      - agent_data:/app/agent_data
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro

  # redis service used as a persistent storage
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ngrok for local tunneling
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok-config.yml:/etc/ngrok.yml
    ports:
      - 4040:4040

  ### Telephony servers ###
  voiceaiagent-inbound-server:
    image: voiceaiagent-inbound-server
    build:
      context: ..
      dockerfile: local_setup/dockerfiles/voiceaiagent-inbound-server.Dockerfile
    ports:
      - "5000:5000"
      - "5002:5002" # Map FastAPI port
    depends_on:
      - redis
    env_file:
      - .env

  voiceaiagent-twilio-app:
    image: voiceaiagent-twilio-app
    build:
      context: ..
      dockerfile: local_setup/dockerfiles/voiceaiagent-twilio-app.Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - ngrok
      - voiceaiagent-app
    env_file:
      - .env